trigger:
- develop

pool:
  vmImage: ubuntu-latest

steps:

- task: BrowserStackConfig@0
  inputs:
    BrowserStackServiceEndPoint: 'Bhagyesh''s Connection'

- task: CmdLine@2
  inputs:
    script: |
      cd browserstack-examples-appium-nunit
      export CAPABILITIES_FILENAME=capabilities.yml
      dotnet restore
      dotnet build
      dotnet test

- task: BrowserStackResults@1
  inputs:
    browserstackProduct: 'App Automate'
